[General]
AlternativeFile=ini\Clean Greyscale.ini

[MacType]
RedrawDelay=5000
AutoEnable=1
HideDenied=1
AutoUnload=1
AutoRun=1
LoadType=1
Use64Agent=1
HideACD=1
Language=2

[UnloadDll]
; List of .exes that don't support MacType, or have no GUI
font-tuner.exe
AdobeIPCBroker.exe
BlackOps3.exe
CCXProcess.exe
ConEmuC.exe
ConEmuC64.exe
Cyberpunk2077.exe
DaysGone.exe
HogwartsLegacy.exe
JediSurvivor.exe
LSB.exe
Lethal Company.exe
MsMpEng.exe
NVDisplay.Container.exe
OfficeClickToRun.exe
QHActiveDefense.exe
QHSafeTray.exe
QHWatchdog.exe
RobloxPlayer.exe
RobloxPlayerBeta.exe
RuntimeBroker.exe
SearchFilterHost.exe
SearchIndexer.exe
SearchProtocolHost.exe
Stardew Valley.exe
SynTPEnh.exe
SynTPHelper.exe
VBoxSVC.exe
VirtualBox.exe
audiodg.exe
cyberpunk2077.exe
dwm.exe
ffxiv.exe
fontforge.exe
igfxCUIService.exe
igfxEM.exe
igfxHK.exe
lass.exe
node.exe
pia-service.exe
services.exe
spoolsv.exe
stacsv64.exe
starwarsjedifallenorder.exe
taskhostw.exe
vmnat.exe
vmnetdhcp.exe
vmware-authd.exe
vmware-usbarbitrator64.exe
vmware-vmx.exe
xd.exe
