//! UI strings. Japanese when the OS UI language is Japanese, English otherwise.

use windows::Win32::Globalization::GetUserDefaultUILanguage;

#[derive(Clone, Copy)]
pub struct Strings {
    pub enabled: &'static str,
    pub profile: &'static str,
    pub reload: &'static str,
    pub version: &'static str,
    pub sysfont: &'static str,
    pub sysfont_default: &'static str,
    pub exit: &'static str,
    pub restart: &'static str,
    pub tip_on: &'static str,
    pub tip_off: &'static str,
    pub err_no_dll: &'static str,
    pub err_hook: &'static str,
    pub err_rva: &'static str,
    pub err_stale: &'static str,
    pub err_already: &'static str,
    // Custom-profile dialog.
    pub custom: &'static str,
    pub custom_edit: &'static str,
    pub custom_title: &'static str,
    pub custom_hinting: &'static str,
    pub custom_hint_native: &'static str,
    pub custom_hint_none: &'static str,
    pub custom_hint_auto: &'static str,
    pub custom_aa: &'static str,
    pub custom_aa_grey: &'static str,
    pub custom_lcd_filter: &'static str,
    pub custom_filter_none: &'static str,
    pub custom_filter_default: &'static str,
    pub custom_filter_light: &'static str,
    pub custom_filter_legacy: &'static str,
    pub custom_gamma_mode: &'static str,
    pub custom_gm_power: &'static str,
    pub custom_gm_avg: &'static str,
    pub custom_gm_linear: &'static str,
    pub custom_gamma: &'static str,
    pub custom_contrast: &'static str,
    pub custom_weight: &'static str,
    pub custom_embolden: &'static str,
    pub custom_font: &'static str,
    pub custom_font_pick: &'static str,
    pub custom_copy: &'static str,
    pub custom_apply: &'static str,
    pub custom_close: &'static str,
    pub custom_sample: &'static str,
    pub custom_err_appdata: &'static str,
    pub custom_err_select: &'static str,
    /// Shown in the dialog for greyscale + FreeType auto-hinter.
    pub custom_warn_grey_autohint: &'static str,
}

const EN: Strings = Strings {
    enabled: "Enabled",
    profile: "Profile",
    reload: "Reload profile (running apps)",
    version: "Version",
    sysfont: "System font",
    sysfont_default: "Default (restore)",
    exit: "Exit",
    restart: "Restart Font-tuner",
    tip_on: "Font-tuner - on",
    tip_off: "Font-tuner - off",
    err_no_dll: "RenderCore64.dll not found. Put font-tuner.exe in the Font-tuner folder.",
    err_hook: "Failed to install the hook.",
    err_rva: "RenderCore64.dll is not laid out as expected (GetMsgProc is not at RVA 0x1000). Hook not installed: it would crash every process that still holds an older core.",
    err_stale: "These programs still hold an older RenderCore64.dll; hooking now would crash them. Sign out and back in (or reboot), then enable Font-tuner:",
    err_already: "Font-tuner is already running.",
    custom: "Custom",
    custom_edit: "Adjust custom...",
    custom_title: "Font-tuner - Custom profile",
    custom_hinting: "Hinting",
    custom_hint_native: "Font's own (bytecode)",
    custom_hint_none: "None",
    custom_hint_auto: "FreeType auto-hinter",
    custom_aa: "Anti-aliasing",
    custom_aa_grey: "Greyscale",
    custom_lcd_filter: "LCD filter",
    custom_filter_none: "None",
    custom_filter_default: "Default",
    custom_filter_light: "Light",
    custom_filter_legacy: "Legacy",
    custom_gamma_mode: "Gamma mode",
    custom_gm_power: "Power (GammaValue)",
    custom_gm_avg: "sRGB / linear average",
    custom_gm_linear: "Linear",
    custom_gamma: "Gamma",
    custom_contrast: "Contrast",
    custom_weight: "Render weight",
    custom_embolden: "Bold (NormalWeight)",
    custom_font: "Preview font",
    custom_font_pick: "Font...",
    custom_copy: "Copy from current profile",
    custom_apply: "Apply",
    custom_close: "Close",
    custom_sample: "The quick brown fox 0123456789 水面に映る文字 あいう アイウ 亜細亜",
    custom_err_appdata: "APPDATA is not set; cannot save the custom profile.",
    custom_err_select: "could not write AlternativeFile=",
    custom_warn_grey_autohint: "Greyscale + auto-hinter: capital heights come out uneven at small sizes (C/3 taller, Z shorter). Prefer the font's own hinting, or use LightLCD with the auto-hinter.",
};

const JA: Strings = Strings {
    enabled: "有効",
    profile: "プロファイル",
    reload: "プロファイルを再読み込み (起動中のアプリに反映)",
    version: "バージョン",
    sysfont: "システムフォント",
    sysfont_default: "既定に戻す",
    exit: "終了",
    restart: "Font-tuner を再起動",
    tip_on: "Font-tuner - 有効",
    tip_off: "Font-tuner - 無効",
    err_no_dll: "RenderCore64.dll が見つからない。font-tuner.exe を Font-tuner のフォルダに置く。",
    err_hook: "フックを張れなかった。",
    err_rva: "RenderCore64.dll の配置が想定と違う (GetMsgProc が RVA 0x1000 にない)。古いコアを保持したままのプロセスが全部落ちるため、フックを張らない。",
    err_stale: "古い RenderCore64.dll を保持したままのプログラムがある。今フックを張るとそれらが落ちる。サインアウトして入り直す (または再起動) してから有効にする:",
    err_already: "Font-tuner はすでに起動している。",
    custom: "カスタム",
    custom_edit: "カスタムを調整...",
    custom_title: "Font-tuner - カスタムプロファイル",
    custom_hinting: "ヒンティング",
    custom_hint_native: "フォント内蔵 (バイトコード)",
    custom_hint_none: "なし",
    custom_hint_auto: "FreeType オートヒント",
    custom_aa: "アンチエイリアス",
    custom_aa_grey: "グレースケール",
    custom_lcd_filter: "LCD フィルタ",
    custom_filter_none: "なし",
    custom_filter_default: "標準",
    custom_filter_light: "ライト",
    custom_filter_legacy: "レガシー",
    custom_gamma_mode: "ガンマモード",
    custom_gm_power: "べき乗 (ガンマ値)",
    custom_gm_avg: "sRGB と線形の平均",
    custom_gm_linear: "線形",
    custom_gamma: "ガンマ値",
    custom_contrast: "コントラスト",
    custom_weight: "レンダーウェイト",
    custom_embolden: "太さ (NormalWeight)",
    custom_font: "プレビューフォント",
    custom_font_pick: "フォント...",
    custom_copy: "現在のプロファイルから複製",
    custom_apply: "適用",
    custom_close: "閉じる",
    custom_sample: "水面に映る文字 あいう アイウ 亜細亜 The quick fox 0123",
    custom_err_appdata: "APPDATA が未設定のためカスタムプロファイルを保存できない。",
    custom_err_select: "AlternativeFile= を書き込めなかった",
    custom_warn_grey_autohint: "グレースケール × オートヒントは小さいサイズで大文字の高さが揃わない (C や 3 が大きく、Z が小さい)。フォント内蔵にするか、オートヒントは LightLCD と組み合わせる",
};

pub fn current() -> Strings {
    // Primary language id 0x11 = Japanese.
    // SAFETY: no arguments, no preconditions.
    let lang = unsafe { GetUserDefaultUILanguage() };
    if lang & 0x3ff == 0x11 { JA } else { EN }
}
